### ISSUE TITLE
Widget can not show in jupyter notebook 

### ISSUE THREAD

**Issue by bangqianchen** [lux-org/lux#107]
I used follow commend to instal lux widget.
    pip install git+https://github.com/lux-org/lux-widget
    jupyter nbextension install --py luxWidget
    jupyter nbextension enable --py luxWidget

It's ok but the widget is not appear in Jupyter notebook. My environment is conda 4.8.5. and Python is 3.7.8.

**Comment by dorisjlee** [comment]
Hi @bangqianchen, 
Here are [some additional resources](https://lux-api.readthedocs.io/en/latest/source/guide/FAQ.html#the-lux-jupyter-widget-does-not-show-up-when-i-print-a-dataframe) for how to troubleshoot the lux-widget installation.
If none of these work, could you attach a screenshot or some additional information about what you see when you print out a dataframe in your notebook, so we can help debug the issue? 
Thanks!

**Comment by bangqianchen** [comment]
Hi, @dorisjlee. I have run jupyter nbextension list, and conformed that the extension is ok. Here is the output:
Known nbextensions:
  config dir: C:\Users\JackDell\.jupyter\nbconfig
    notebook section
      bqplot/extension enabled
      - Validating: ok
      ipytree/extension enabled
      - Validating: ok
      jupyter-leaflet/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
      hinterland/hinterland enabled
      - Validating: ok
      codefolding/main enabled
      - Validating: ok
      code_prettify/code_prettify disabled
      spellchecker/main enabled
      - Validating: ok
      toggle_all_line_numbers/main enabled
      - Validating: ok
      highlighter/highlighter enabled
      - Validating: ok
      highlight_selected_word/main enabled
      - Validating: ok
      help_panel/help_panel enabled
      - Validating: ok
      code_font_size/code_font_size disabled
      toc2/main enabled
      - Validating: ok
      **luxWidget/extension enabled
      - Validating: ok**
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
    edit section
      ruler/edit disabled
  config dir: C:\ProgramData\Anaconda3\etc\jupyter\nbconfig
    notebook section
      bqplot/extension enabled
      - Validating: ok
      ipytree/extension enabled
      - Validating: ok
      jupyter-leaflet/extension enabled
      - Validating: ok
      voila/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main

It does not show the widget when I run such script:
![2020-10-09_150448](https://user-images.githubusercontent.com/20618654/95553336-f1739280-0a40-11eb-9391-89d98adf051c.png)

**Comment by dorisjlee** [comment]
Hi @bangqianchen, 

What is the size of the dataframe that you are visualizing? If the dataframe is less than 10 rows, then the dataframe would not be visualized. Could you try testing your installation on this [example notebook](https://github.com/lux-org/lux/blob/master/examples/demo/cars_demo.ipynb) to see if this is working?  Thank you!

**Comment by bangqianchen** [comment]
There area 51 rows in my dataframe. I follow your testing by do not have  'car.csv' file on my computer.


![Untitled](https://user-images.githubusercontent.com/20618654/95693548-87850400-0c5f-11eb-8d60-be3b0d655c30.jpg)

**Comment by bangqianchen** [comment]
Here is my file structure in C:\ProgramData\Anaconda3\Lib\site-packages, I am not sure whether it's ok.
├─lux
│  ├─core
│  │  ├─commands
│  │  │  ├─project_template
│  │  │  │  └─js
│  │  │  └─__pycache__
│  │  ├─templates
│  │  └─__pycache__
│  ├─extensions
│  │  ├─admin
│  │  │  └─__pycache__
│  │  ├─applications
│  │  │  ├─commands
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─auth
│  │  │  ├─commands
│  │  │  │  └─__pycache__
│  │  │  ├─rest
│  │  │  │  └─__pycache__
│  │  │  ├─templates
│  │  │  │  └─registration
│  │  │  └─__pycache__
│  │  ├─base
│  │  │  └─__pycache__
│  │  ├─content
│  │  │  ├─commands
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─oauth
│  │  │  ├─amazon
│  │  │  │  └─__pycache__
│  │  │  ├─dropbox
│  │  │  │  └─__pycache__
│  │  │  ├─facebook
│  │  │  │  └─__pycache__
│  │  │  ├─github
│  │  │  │  └─__pycache__
│  │  │  ├─google
│  │  │  │  └─__pycache__
│  │  │  ├─linkedin
│  │  │  │  └─__pycache__
│  │  │  ├─twitter
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─odm
│  │  │  ├─commands
│  │  │  │  ├─template
│  │  │  │  │  └─lux
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─organisations
│  │  │  ├─templates
│  │  │  │  └─user
│  │  │  └─__pycache__
│  │  ├─rest
│  │  │  ├─api
│  │  │  │  └─__pycache__
│  │  │  ├─commands
│  │  │  │  └─__pycache__
│  │  │  ├─views
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─sessions
│  │  │  ├─commands
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─sitemap
│  │  │  ├─commands
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  ├─smtp
│  │  │  └─__pycache__
│  │  ├─sockjs
│  │  │  ├─rpc
│  │  │  │  └─__pycache__
│  │  │  ├─transports
│  │  │  │  └─__pycache__
│  │  │  └─__pycache__
│  │  └─__pycache__
│  ├─forms
│  │  └─__pycache__
│  ├─utils
│  │  ├─crypt
│  │  │  └─__pycache__
│  │  └─__pycache__
│  └─__pycache__
├─lux-0.8.2.dist-info
├─luxWidget
│  ├─nbextension
│  │  ├─static
│  │  └─__pycache__
│  └─__pycache__
├─luxWidget-0.1.0.dist-info

**Comment by dorisjlee** [comment]
Hi @bangqianchen, 
You can download the cars.csv [here](https://github.com/lux-org/lux/blob/master/lux/data/car.csv) or you can clone the Github repository and run the notebooks inside [examples/](https://github.com/lux-org/lux/tree/master/examples), which should contain the right path to the relevant data files. We've also recently released [version 0.2.0](https://github.com/lux-org/lux/releases/tag/v0.2.0) of Lux which simplifies the installation process quite a bit, so if you are still experiencing issues with the Lux widget on the example notebooks. I would encourage you to uninstall the earlier version of lux and luxWidget and follow the [new, simplified instructions for installation](https://github.com/lux-org/lux#quick-installation). Hopefully, this should make things work more smoothly. Please let me know if you are still experiencing issues with this or whether any one of these approaches works for you. Thanks!

**Comment by bangqianchen** [comment]
Dear Doris,

  Many thanks for your kindly reply. The new version is ok on my computer
now. Great!

**Comment by dorisjlee** [comment]
That's great to hear @bangqianchen! Please feel free to reach out to us if you experiencing additional issues with Lux. We're actively working on the project and would love feedback on how to make it better.

**Comment by dorisjlee** [comment]
Hi @bangqianchen, 
Could you try the installation commands without the `--sys-prefix --symlink --overwrite` options? 
Something like the following: 
```
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
You find the [new, simplified instructions for installation](https://github.com/lux-org/lux#quick-installation) here. 
Thanks!

**Comment by bangqianchen** [comment]
Yea, it works now. Thank you very much.
