### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by akanz1** [lux-org/lux#110]
Hey Team Lux,

i just installed Lux and the nbextension as described in the Qiuck install section to explore its capabilities and ran into the following error message after hitting the "Toggle Pandas/Lux" button.

![Screenshot 2020-10-10 192342](https://user-images.githubusercontent.com/51492342/95661291-6ec90100-0b2e-11eb-8c57-008414bcc6c9.png)

```import lux``` runs without any complaint and running ```lux.version_info``` returns (0, 2, 0). Also, when installing i got ```Validating: OK``` for both nbextension commands.

I'm running this in the latest version of chrome, python 3.7.8 and pandas 1.1.3.

**Comment by dorisjlee** [comment]
Hi @akanz1, 

Thank you for your interest in Lux!
I took a look at the issue that you described and was able to reproduce the issue in JupyterLab.
<img src="https://user-images.githubusercontent.com/5554675/95668236-bfc70c80-0ba3-11eb-9f98-4d6feb459b37.png" width=500></img>
From the screenshot, it looks like you might be using JupyterLab or opening a notebook inside VSCode? 
Lux does not currently support JupyterLab, this is an [issue](https://github.com/lux-org/lux-widget/issues/16) that we are hoping to work on in the future. 
Could you try using the basic Jupyter notebook via the `jupyter notebook` command and see if Lux works there? Here is an [example notebook](https://github.com/lux-org/lux/blob/master/examples/demo/cars_demo.ipynb) that you can use to test if the widget shows up.

**Comment by akanz1** [comment]
Thank you for getting back to me @dorisjlee,

forking lux and running the example in jupyter notebook does indeed produce the desired behavior! 👍 

However, running my minimal example above in jupyter notebook, lab (used initially) or vscode (getting: Error: Module luxwidget, semver range 0.1.0 is not registered as a widget module) does not work. It does however produce an output for larger dataframes in jupyter notebook (as long as there are no print statements in the same cell).

```print(df.shape)
df```

This does not show the widget, while ```df``` does.

Does lux require a minimum number of datapoints before it starts making suggestions?

Looking forward to future versions! :)

**Comment by dorisjlee** [comment]
Great, glad that the example notebook is working in your jupyter notebook!

You're right that Lux requires a minimum number of data points (i.e., at least 10 rows in the dataframe) before it starts making the recommendations. The idea is that the default Pandas table is most likely sufficient for looking at such a small dataframe. If the small dataframe is a result of some aggregation, we do try to suggest relevant visualizations. I've added an issue (#111) to make this explanation more clear to the users in the future .

Thanks for the helpful suggestions! Lux is still an early-stage project, so please don't hesitate to reach out if you run into any issues. We'd love to hear about how you're using Lux!

**Comment by akanz1** [comment]
I agree, that makes sense, thanks again!
