### ISSUE TITLE
No module named 'luxwidget' when installing and activating the api

### ISSUE THREAD

**Issue by Smartog** [lux-org/lux#113]
The console leaves me a "ModuleNotFoundError: No module named 'luxwidget'" when i try to run "jupyter nbextension install --sys-prefix --symlink --overwrite --py luxwidget" in cmd.

**Comment by dorisjlee** [comment]
Hi @Smartog,

You can follow the quick install instructions [here](https://github.com/lux-org/lux#quick-installation).
When you do `pip freeze` do you see `lux-widget` listed under one of the installations? 
`lux-widget` should have been installed when you did `pip install lux-api` as the first installation step. 
If not, you may want to do `pip install lux-widget` to install it directly. 
Please let me know if you are still experiencing issues.

**Comment by Smartog** [comment]
Yeal,It works! @dorisjlee ,
After running the "pip freeze", I found the "luxWidget==0.0.7" and  the letter "w" is capital that is why I failed when spelling it "luxwidget".

Yet,another problem occurred when I tried to run:
`import lux
import pandas as pd
df = pd.read_csv("college.csv")
df
`

There should be a buttom to show the picture below but i cannot find it. 
The error indication is:
`
d:\python3.8.6\lib\site-packages\IPython\core\formatters.py:345: UserWarning: 
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.

Please report this issue on Github: https://github.com/lux-org/lux/issues 
  return method()
`

**Comment by Smartog** [comment]
@dorisjlee 
sorry,the code I run is:
`import lux`
`import pandas as pd`
`df = pd.read_csv("college.csv")`
`df`
I am a freshman in the github editor.

**Comment by dorisjlee** [comment]
Hi @Smartog, 

It seems like you have an older version of luxwidget (in v0.0.7, we had the capital luxWidget, but we have changed it in the latest version). So it's likely that your luxwidget and lux-api versions are not in sync. I would encourage you to install both your lux-api and lux-widget:
```
pip uninstall lux-api
pip uninstall lux-widget

jupyter nbextension uninstall --py luxWidget
jupyter nbextension disable --py luxWidget
```
Then try doing the install again (the new lux-api should just install the widget for you directly): 
```
pip install lux-api

 jupyter nbextension install --py luxwidget
 jupyter nbextension enable --py luxwidget
```

**Comment by Smartog** [comment]
Thank you !!!@dorisjlee
Following your tips，I‘ve succeded solving the problem, that's amazing.... and I am very excited!
Thank you for your patience!!! I believe this api would enjoy more popularity in the future.

**Comment by dorisjlee** [comment]
Hi @Smartog, It's great to hear that it is working now. Thank you for your interest in our project. Lux still an early-stage project, so please don't hesitate to reach out if you run into any issues. We'd also love to hear about how you're using Lux!
