### ISSUE TITLE
New Action: Automatic geographic attribute visualizations

### ISSUE THREAD

**Issue by dorisjlee** [lux-org/lux#123]
For geo-related attributes (longitude, latitude, state, countries, etc), we should detect it as a special data type and display a choropleth automatically.

**Comment by micahtyong** [comment]
Hi @dorisjlee, I'm thinking of potentially picking this one up! From my understanding, Lux depends on [Altair](https://altair-viz.github.io/). If that's the case, I would use the [Altair Cloropleth Map](https://altair-viz.github.io/gallery/choropleth.html) to display a choropleth for each non-geo-related quantitative group. More precisely, would a suitable solution to this be a [repeated choropleth map like this example](https://altair-viz.github.io/gallery/choropleth_repeat.html)?

**Comment by dorisjlee** [comment]
Hi @micahtyong, This is a fun issue to work on! What you suggested is a good starting point. We can have a choropleth like this for `states`, where we have a color choropleth for each of the quantitative variables. We probably first need to detect geo-related attribute types first, then implement this as a [custom action](https://lux-api.readthedocs.io/en/latest/source/advanced/custom.html).
