### ISSUE TITLE
Error: script error for “luxwidget”

### ISSUE THREAD

**Issue by alanmluu** [lux-org/lux#141]
There is an issue with displaying the lux widget after I followed the installation commands:
```
pip install lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
I was able to print out a dataframe with the pandas table along with the toggle button. However, when I press the toggle button, the lux widget does not show up. The following error shows up on the Chrome inspector:
![Screen Shot 2020-11-15 at 4 05 37 PM](https://user-images.githubusercontent.com/5554675/99201141-9756b180-27e4-11eb-8cad-a2a0303f2205.png)
The following packages are installed on my virtualenv:
[lux_env_packages.txt](https://github.com/lux-org/lux-widget/files/5543415/lux_env_packages.txt)
This is the result of running `jupyter nbextension list`:

Known nbextensions:
  config dir: /Users/alanluu/.jupyter/nbconfig
    notebook section
      luxWidget/extension  enabled
      - Validating: OK
      luxwidget/extension  enabled
      - Validating: OK
  config dir: /Users/alanluu/Environments/lux_env/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK

**Comment by dorisjlee** [comment]
The issue is resolved after submitting these reinstalling commands: 
```
pip uninstall lux-api
pip uninstall lux-widget

pip install lux-api

jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
The results of `jupyter nbextension list` and `pip freeze` is the same as above, but now the widget can be displayed on the notebook.

**Comment by dorisjlee** [comment]
This issue should be resolved after the luxwidget name change in the latest [v0.1.1 release](https://pypi.org/project/lux-widget/0.1.1/).

**Comment by howardmalec** [comment]
I'm getting the same error when running a notebook on Sagemaker after uninstalling and re-installing the following:

```
!pip uninstall lux-api -y
!pip uninstall lux-widget -y
!pip install lux-api
!pip install lux-widget
!jupyter nbextension install --py luxwidget --user 
!jupyter nbextension enable --py luxwidget
```
