### ISSUE TITLE
[SETUP] Lux Fallback Error

### ISSUE THREAD

**Issue by danilosantiago** [lux-org/lux#162]
\Roaming\Python\Python37\site-packages\IPython\core\formatters.py:338: UserWarning: 
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.

Please report this issue on Github: https://github.com/lux-org/lux/issues 
  return method()

**Comment by dorisjlee** [comment]
Hi @danilosantiago, Thank you for your interest in Lux. We just had an updated release with some bug fixes and a more debuggable printout of the error message. Could you try installing this using the following command?
```
pip install lux-api==0.2.1
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Note that you may have to restart your jupyter notebook after doing this so that the change is reflected.
After this, if you can send a screenshot of the error and the operations that led up to it, it would be very helpful for debugging.

**Comment by danilosantiago** [comment]
Hello 

thank you for this important information 

One question , It will works for jupyter lab or notebooks in databricks ?? 

thank you 

Atentamente: Ing Mat. Danilo Santiago Criollo Chávez (+593)(0)(992496074 ECU)






El domingo, 29 de noviembre de 2020 10:41:08 p. m. GMT-5, Doris Lee <notifications@github.com> escribió: 







Hi @danilosantiago, Thank you for your interest in Lux. We just had an updated release with some bug fixes and a more debuggable printout of the error message. Could you try installing this using the following command?
pip install lux-api==0.2.1
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget

Note that you may have to restart your jupyter notebook after doing this so that the change is reflected.
After this, if you can send a screenshot of the error and the operations that led up to it, it would be very helpful for debugging.

**Comment by dorisjlee** [comment]
Hi @danilosantiago, Lux currently works with Jupyter notebooks. We are planning to support JupyterLab for the next release.

**Comment by dorisjlee** [comment]
Hi @danilosantiago, Addressing issue in #178, could you first update to the latest version of Lux? 
```bash 
pip install --upgrade lux-api
pip install --upgrade lux-widget

jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Then restart your Jupyter notebook to activate the new version.
There should be some information printed before the fallback error, which will be useful for us to debug why the error is showing up. If you can provide any additional screenshot or description of what commands led to this error would also be useful. Thanks!

**Comment by dorisjlee** [comment]
Closing this issue for now. If there is anything that we can help with, please feel free to open a new issue!
