### ISSUE TITLE
Error displaying widget: model not found

### ISSUE THREAD

**Issue by masoudfard** [lux-org/lux#165]
I receive this error:
Error displaying widget: model not found
![Capture](https://user-images.githubusercontent.com/72363702/100577903-5064d200-3335-11eb-97dd-733644bf0304.PNG)

**Comment by dorisjlee** [comment]
Hi @masoudfard, This seems like it is related to #110. Are you using Jupyter Lab or some other notebook interface? Could you try using the basic Jupyter notebook via the `jupyter notebook` command and see if the Lux widget works there?

**Comment by masoudfard** [comment]
@dorisjlee You right. The problem solved in Jupyter notebook. Great work!!
