### ISSUE TITLE
[SETUP] Script Error for luxwidget

### ISSUE THREAD

**Issue by Nadeesha0ekanayake** [lux-org/lux#166]
Lux Jupyter widget does  show up when I print a dataframe but nothing appears as visualization . Output is null .

![image](https://user-images.githubusercontent.com/47077722/100583449-b8ed8800-3310-11eb-81e1-34fa03a4b454.png)

Jupyter nbextensions are also validated

![image](https://user-images.githubusercontent.com/47077722/100583652-fce08d00-3310-11eb-85e4-e5e6c082d47b.png)

**Comment by dorisjlee** [comment]
Hi @Nadeesha0ekanayake, Thank you for trying out Lux! 
Could you try printing the dataframe directly to see if the widget would show up? Following something like: 
```
df2=pd.read_csv("bigmart_data.csv")
df2
```
If you are still having issues with the widget not being displayed, could you go into your Chrome browser inspector (right-click "Inspect" --> click on "Console" tab) and take a screenshot of any errors there?

**Comment by Nadeesha0ekanayake** [comment]
I get the widget and pandas side seems fine . But when i toggle in between nothing happens with Lux 

![image](https://user-images.githubusercontent.com/47077722/100590553-8fd1f500-331a-11eb-907b-c4f21b173691.png)

**Comment by Nadeesha0ekanayake** [comment]
![image](https://user-images.githubusercontent.com/47077722/100590792-e0495280-331a-11eb-87a6-20cb5fe5a32a.png)

**Comment by Nadeesha0ekanayake** [comment]
@dorisjlee  yes there are errors in the console .  But im not much expert to read those . 

![image](https://user-images.githubusercontent.com/47077722/100591459-ce1be400-331b-11eb-817f-d2d8072eba04.png)

**Comment by Nadeesha0ekanayake** [comment]
let me know if u want to expand the errors to read it more

**Comment by dorisjlee** [comment]
Thank you @Nadeesha0ekanayake. We are looking into this issue. This seems to be a similar issue to #141. 
Could you try the following reinstallation commands to see if it helps?
```bash
pip uninstall lux-api
pip uninstall lux-widget

pip install lux-api==0.2.1
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
You probably need to restart your jupyter notebook for this change to take place. Note that Lux currently only supports Jupyter notebook instead of Jupyter Lab.

**Comment by Nadeesha0ekanayake** [comment]
Hi @dorisjlee , im testing this on Jupyter notebooks actually not in Jupyter Lab.

bdw do u mean to say i need to uninstall lux-api and lux-widget both but reinstall only lux api ?? (as per your given installation commands above)

**Comment by cjachekang** [comment]
Hi @Nadeesha0ekanayake, yes that should be fine - installing lux-api installs lux-widget as well!

**Comment by Nadeesha0ekanayake** [comment]
Hi All, After doing following installation commands , my issue solved. 
Thanks so much. Now i get lux widget with all visualizations !!!!
@dorisjlee @cjachekang 
>>>
pip uninstall lux-api
pip uninstall lux-widget
pip install lux-api==0.2.1
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget

**Comment by dorisjlee** [comment]
Thanks @Nadeesha0ekanayake, that is great to hear! Please don’t hesitate to reach out if you run into any additional issues or would like to chat more about how we can improve this for you.
