### ISSUE TITLE
[SETUP] Support for VScode

### ISSUE THREAD

**Issue by ashishpatel1992** [lux-org/lux#167]
Getting following error on vscode
`Error: Module luxwidget, semver range 0.1.1 is not registered as a widget module`

![image](https://user-images.githubusercontent.com/652311/100623702-852e5480-3348-11eb-9b70-2afc1387dc07.png)

**Comment by dorisjlee** [comment]
Hi @ashishpatel1992, This seems like it is related to #110. It looks like you are using the Jupyter interface inside VSCode, which is not currently supported. Lux only operates on Jupyter notebook currently and we plan to add support for Jupyter Lab and other notebook interfaces in the future. Could you try using the classic Jupyter notebook interface via the `jupyter notebook` command and see if the Lux widget works there?

**Comment by jinimukh** [comment]
Hi @ashishpatel1992! Thank you for using Lux and bringing up this issue!
We have incorporated VSCode support in our newest release. To enable this, please make sure to install the jupyter lab extension using the following commands:


`pip install lux-api`
`jupyter nbextension install --py luxwidget`
`jupyter nbextension enable --py luxwidget`
`jupyter labextension install @jupyter-widgets/jupyterlab-manager`
`jupyter labextension install luxwidget`

 For more information on how to set up, see https://lux-api.readthedocs.io/en/latest/source/getting_started/installation.html

Here is a screenshot of what you should see with some test code:
<img width="1641" alt="Screen Shot 2021-01-21 at 10 06 16 PM" src="https://user-images.githubusercontent.com/46768380/105453680-673cec00-5c35-11eb-949d-3f464e8514ae.png">

Please feel free to respond to this issue if you are having any trouble.

**Comment by supernooba** [comment]
I was waiting for this, thank you!

**Comment by tomsing1** [comment]
I have successfully followed the installation instructions and my dataframe is displayed in VSCode via lux - yay!

![Screen Shot 2021-07-24 at 5 54 26 PM](https://user-images.githubusercontent.com/10490984/126884443-7abdb275-1820-49c0-80a4-69aed1d8e042.png)

But when I click on either the `Distribution` or `Occurence` links, VSCode is trying to open a page in my web browser (Brave) that doesn't seem to exist:

![Screen Shot 2021-07-24 at 5 58 40 PM](https://user-images.githubusercontent.com/10490984/126884435-582d991c-dee0-409f-8cab-795f9864b758.png)

But moving between the `Correlation/Distribution/Occurence` tabs using the `Shift + arrow` keyboard shortcuts works.

**Comment by dorisjlee** [comment]
Thanks for pointing this out @tomsing1! I just tested this and noticed the same issue. I've opened a new issue for this and we will take a look at how to fix this soon!
