### ISSUE TITLE
[SETUP] Jupyter Notebook Extension requires YAML file

### ISSUE THREAD

**Issue by PreetiKumariUAH** [lux-org/lux#171]
I receive an error message when I try to use lux widget in jupyter. Can you share the yaml file?

"**luxwidget/extension**
This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it. You can still enable or disable it from here, though."
![Capture](https://user-images.githubusercontent.com/75446725/101073353-ef234580-3564-11eb-8a52-a4259ea5bebe.PNG)

**Comment by jinimukh** [comment]
Hi! Thanks so much for using Lux. 
For installation, did you run:

```
pip install lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```

**Comment by dorisjlee** [comment]
Thanks @PreetiKumariUAH, the last two commands that @jinimukh posted should enable the widget extension.
```
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Let us know if this works for you!

**Comment by Berk12345** [comment]
Hello @dorisjlee @jinimukh . I wrote the last two commands to activate lux in Jupyter Notebook but I got this error. How can I fix this?

` File "<ipython-input-14-80b21bf5cf15>", line 1
    jupyter nbextension install --py luxwidget
                      ^
SyntaxError: invalid syntax`

**Comment by jinimukh** [comment]
Hi @Berk12345 
You will need to run these in your terminal, not the jupyter notebook. Let us know if there is still a problem!

**Comment by Berk12345** [comment]
@jinimukh Thanks a lot for your advice. It worked. Have a nice day!
