### ISSUE TITLE
[SETUP] Clicking on toggle button does not display any graphs

### ISSUE THREAD

**Issue by kandasamy11** [lux-org/lux#172]
I loaded the iris dataset to test the functionality and I do see the toggle button to alternate between looking at the dataframe and the visualizations. However, clicking the toggle button does not display any graphs.

I used !jupyter nbextension list to check if the widget is activated and the validation is ok with the extension enabled.

**Comment by kandasamy11** [comment]
![image](https://user-images.githubusercontent.com/42836518/101108442-7d69ec80-35a2-11eb-9065-fc373063989a.png)

**Comment by dorisjlee** [comment]
Hi @kandasamy11, Thank you for your question. Are you using Jupyter notebook on Chrome? To help us debug, could you go into your Chrome browser inspector (right-click "Inspect" --> click on "Console" tab) and take a screenshot of any errors there? This is possibly related to a similar issue in #166.

**Comment by sacredsoul98** [comment]
> Hi @kandasamy11, Thank you for your question. Are you using Jupyter notebook on Chrome? To help us debug, could you go into your Chrome browser inspector (right-click "Inspect" --> click on "Console" tab) and take a screenshot of any errors there? This is possibly related to a similar issue in #166.
Here are the errors I get for the same issue
![Screenshot (86)](https://user-images.githubusercontent.com/29597558/101606829-d36ae400-3a29-11eb-8fd6-75cdfd5939ca.png)

**Comment by dorisjlee** [comment]
Hi @sacredsoul98, @kandasamy11 ,
Could you try reinstalling lux via the following commands to see if this fixes the issue?

```
pip uninstall lux-api
pip uninstall lux-widget

pip install lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Thanks!

**Comment by kandasamy11** [comment]
Hi @dorisjlee reinstalling lux worked for me. Thank you!

**Comment by dorisjlee** [comment]
Thanks for letting us know, that's great to hear!
