### ISSUE TITLE
[Q] How to visualise outliers using lux?

### ISSUE THREAD

**Issue by SurendranRavimathi** [lux-org/lux#173]
I started using lux for my project
Where i use VisList more thanks for that 

Issue here is 

Some cases i need visualise outliers using boxplot

Is there any option available?
Kindly me out !
For this one reason i am  using seaborn in my project

**Comment by dorisjlee** [comment]
Hi @SurendranRavimathi, Thank you for your question. Could you describe the outlier visualization that you would like and the VisList associated with this in more detail?

**Comment by SurendranRavimathi** [comment]
I used titanic data set from kaggle 
Here  target is Survived
 I compared fare and Survived

I tried to create dummies for fare with frequency cutoff 

I used seaborn to create box plot 
to visuvalise where the outliers starts and where 
Target effecting values is ranging
 
I found it is approximately 100

In that most cases i used lux 

Vis
Vislist
Intent

But  i wouldn't find anything 
I tried in Google search and your github description at lux-org 

Still i didn't the proper guide to 
Visualize outliers in the data 

Like boxplot 

So kindly help me to use lux instead of matplot

I believe that it will!

Thanks for creating such library ❤️

**Comment by jinimukh** [comment]
Hi! Thank you for using Lux!

All of our tutorials are located at https://github.com/lux-org/lux-binder/tree/master/tutorial. For more details, our documentation is located at https://lux-api.readthedocs.io/en/latest/

We currently don't support box-plots or using the seaborn plotting library though we do want to in the future. (Our plotting is done with a library called altair: https://github.com/altair-viz/altair)

We welcome any contributions! Thanks!
