### ISSUE TITLE
[SETUP] Failed building wheel for scikit-learn

### ISSUE THREAD

**Issue by vmreyes12** [lux-org/lux#186]
I  am working on a Ubuntu 18.04.5 LTS machine, and I am trying to install lux-api using pip as described in the docs. My installation exits on the following error:

error: Command "x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.7/dist-packages/numpy/core/include -I/usr/local/lib/python3.7/dist-packages/numpy/core/include -I/usr/include/python3.7m -c sklearn/__check_build/_check_build.c -o build/temp.linux-x86_64-3.7/sklearn/__check_build/_check_build.o -MMD -MF build/temp.linux-x86_64-3.7/sklearn/__check_build/_check_build.o.d -fopenmp" failed with exit status 1

Any help will be great! Thanks

**Comment by dorisjlee** [comment]
Hi @vmreyes12, Thanks for your interest in Lux! This looks like an issue with the sklearn installation. Perhaps you could try [installing sklearn](https://scikit-learn.org/stable/install.html) independently first:
```python
pip3 install -U scikit-learn
```
then if that is successful, you can install lux-api. Hopefully that could isolate the error and help you debug the issue.
