### ISSUE TITLE
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.

### ISSUE THREAD

**Issue by powermap** [lux-org/lux#242]
C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
Please report the following issue on Github: https://github.com/lux-org/lux/issues 

C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\lux\core\frame.py:653: UserWarning:Traceback (most recent call last):
  File "C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\lux\core\frame.py", line 592, in _repr_html_
    return []
  File "C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\lux\core\frame.py", line 109, in maintain_metadata
    if not hasattr(self, "_metadata_fresh") or not self._metadata_fresh:
  File "C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\lux\executor\PandasExecutor.py", line 504, in compute_stats
  File "C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\generic.py", line 11475, in stat_func
    func, name=name, axis=axis, skipna=skipna, numeric_only=numeric_only
  File "C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\series.py", line 4249, in _reduce
    return op(delegate, skipna=skipna, **kwds)
  File "C:\Users\power\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\nanops.py", line 120, in f
    result = bn_func(values, axis=axis, **kwds)
TypeError: 'NoneType' object is not callable

used "pip install lux-api==0.2.1
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget"，But it's still wrong.

**Comment by dorisjlee** [comment]
Hi @powermap, Thanks for reporting this issue! Could you check if using the latest version 0.2.2 resolves this issue? 
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
If not, it would be very helpful if you could provide a sample of the data to help us reproduce the error. Thanks!

**Comment by powermap** [comment]
"import lux
lux.version_info
(0, 2, 2)" used 0, 2, 2 ,but it's still wrong.  python 3.6.7 64bit

**Comment by dorisjlee** [comment]
Ok I see, we can look into this issue. Could you send us a sample of the dataset that led to this error so that we can reproduce this issue? Thanks!

**Comment by powermap** [comment]
[College.zip](https://github.com/lux-org/lux/files/5863990/College.zip)

**Comment by powermap** [comment]
in Nbextensions configuration   
"luxwidget/extension
This nbextension is enabled in the notebook json config, but doesn't provide a yaml file to tell us how to configure it. You can still enable or disable it from here, though.
section: notebook
require path: luxwidget/extension
**compatibility: ?.x**" .

Is there a compatibility problem？

**Comment by caitlynachen** [comment]
Hi @powermap! Have you tried running `jupyter contrib nbextension`?

**Comment by powermap** [comment]
Hi @dorisjlee！ It's can   running jupyter contrib nbextension。   my pandas version is 1.1.5，Is version supported？

**Comment by caitlynachen** [comment]
Hi @powermap ! yes, anything after 1.1.0 pandas should be supported

**Comment by caitlynachen** [comment]
@powermap 

- are you able to render a basic Lux widget in jupyter (https://github.com/lux-org/lux-binder/blob/master/tutorial/0-overview.ipynb)?
- what does `jupyter nbextension list` include for your machine?

Thanks!

**Comment by powermap** [comment]
@dorisjlee 
![2021-01-26_9-25-09](https://user-images.githubusercontent.com/6008205/105786693-87afd200-5fb8-11eb-9a76-eaed955683aa.png)

**Comment by powermap** [comment]
@dorisjlee  “are you able to render a basic widget in jupyter ” yes，it can

**Comment by dorisjlee** [comment]
Hi @powermap, Thanks for letting us know! If you are able to render a basic in Jupyter, then it most likely have little to do with compatibility problem that you pointed to in the nbextension config. I just tried using the CSV that you attached above to print out the dataframe and it seems to be working. Was there specific commands that led to the errors that you posted above? 
![image](https://user-images.githubusercontent.com/5554675/105833982-e69b3880-6004-11eb-9f8e-3dad219e464d.png)

**Comment by powermap** [comment]
Hi@dorisjlee，
Maybe it's a python version problem. I didn't have this problem with Python 3.7.6 。

**Comment by cjachekang** [comment]
Hi @powermap , we recently pushed Lux onto conda-forge to help with compatibility with lux and anaconda. Could you try install via `conda install -c conda-forge `lux-api` and see if that helps? Let us know how it goes and if the issue persists, feel free to reopen this issue.

**Comment by vivnlamb** [comment]
TypeError: groupby() got an unexpected keyword argument 'dropna'

**Comment by Taykehrle** [comment]
![image](https://user-images.githubusercontent.com/86122881/129075286-57e9414d-4805-4a58-9707-7486b44a34af.png)

**Comment by Taykehrle** [comment]
What i can do?
