### ISSUE TITLE
AttributeError: 'VisList' object has no attribute 'topK'

### ISSUE THREAD

**Issue by vnnw** [lux-org/lux#255]
I followed the tutorial of https://hub.gke2.mybinder.org/user/lux-org-lux-binder-85yxv12x/notebooks/tutorial/8-custom-action.ipynb, when run the codes below, I got an AttributeError:
```
for vis in vlist:
    # Percentage Change Between G10 v.s. non-G10 countries 
    a = vis.data.iloc[0,1]
    b = vis.data.iloc[1,1]
    vis.score = (b-a)/a
vlist = vlist.topK(15)

AttributeError                            Traceback (most recent call last)
<ipython-input-5-500c1e16d3f4> in <module>
      7     b = vis.data.iloc[1,1]
      8     vis.score = (b-a)/a
----> 9 vlist = vlist.topK(15)

AttributeError: 'VisList' object has no attribute 'topK'
```

**Comment by dorisjlee** [comment]
Hi @vnnw, Thanks for raising this issue! We changed the `vlist.topK` function to `vlist.showK` to accommodate top and bottom K in the latest version. We will fix this in our documentation soon.

**Comment by micahtyong** [comment]
Hi @vnnw, I've just opened up two pull requests that should resolve the issues you faced. Hope this helps!
