### ISSUE TITLE
Feature Request: add correlation algorithms?

### ISSUE THREAD

**Issue by vnnw** [lux-org/lux#257]
I think it is possible and valuable for Lux to add more correlation algorithms for ordinal/ categorial data, maybe like what Pandas-profiling has done: https://github.com/pandas-profiling/pandas-profiling/blob/develop/src/pandas_profiling/model/correlations.py?

**Comment by dorisjlee** [comment]
Hi @vnnw, Thanks for your question. Lux currently supports Pearson's correlation score for the Correlation action. If you are interested in other types of correlation metrics, you can define your own custom action with the correlation metrics in Lux. To learn more about how you could register your own actions, please check out this [documentation page](https://lux-api.readthedocs.io/en/latest/source/advanced/custom.html). Let us know if this addresses your issue!

**Comment by dorisjlee** [comment]
Hi @vnnw, Closing this for now. Please feel free to open a new issue if you have any other questions!
