### ISSUE TITLE
[SETUP] Frontend widget not displayed

### ISSUE THREAD

**Issue by Winnergy** [lux-org/lux#258]
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
![09-02-2021 11-26-05](https://user-images.githubusercontent.com/78793855/107350392-adb19800-6ac9-11eb-9613-c41b6e91fde4.jpg)

**Comment by dorisjlee** [comment]
Hi @Winnergy, Thanks for reporting this issue. Could you provide us with a sample of the dataset and the set of commands that led to this error? Could you also check if upgrading to the latest version of Lux resolves this issue?
```
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Thanks!

**Comment by Winnergy** [comment]
Hi Doris,
Sure, here below the code:

import lux
import pandas as pd
df = pd.read_csv("C:\\Users\\CATNESS\Desktop\\QCS\\SUNFLOWER_GENOME\\Sunflower challenge 2021\\PREDICT_20210205\\RESULTS_3402_ANALYSIS_CLEAN.csv", ';')
df.intent = ['Cultivar','Location', 'NB_Y', 'Experiment', 'Yield', 'Center', 'MAX', 'MIN', 'ADABOOST', 'NN']
df

**Comment by Winnergy** [comment]
Here is the attachment, sorry.
[RESULTS_3402_ANALYSIS_CLEAN.zip](https://github.com/lux-org/lux/files/5950789/RESULTS_3402_ANALYSIS_CLEAN.zip)

**Comment by Winnergy** [comment]
I have updated to the last version.
It does not solve the issue.
I have updated pandas as well
The JupyterLab version is 2.2.6

**Comment by dorisjlee** [comment]
Hi @Winnergy, Thanks for sending this information over. It looks like I am able to print out the visualization for your dataset correctly without the error. Was there specific commands that led to the issue that you posted above?

```python
import pandas as pd
import lux
df = pd.read_csv("RESULTS_3402_ANALYSIS_CLEAN.csv",delimiter=";")
df['NB_Y'] = pd.to_datetime(df['NB_Y'], format='%Y')
```
![image](https://user-images.githubusercontent.com/5554675/107360304-b083ab80-6b10-11eb-82fc-27f15157f9e6.png)
![image](https://user-images.githubusercontent.com/5554675/107360279-a8c40700-6b10-11eb-988d-2972d3b0619b.png)

**Comment by Winnergy** [comment]
Doris,

Many thanks for your time and for the answer.
I have updated Python and now I get only a table.

Is there something I miss in my installation because I don't have any
graphic representation?

Kind Regards,
Catalin

[image: image.png]

**Comment by dorisjlee** [comment]
Hi @Winnergy, You mentioned that you were using Jupyter Lab as the notebook frontend. Did you run the jupyter labextension commands after the pip install command?
```python
pip install lux-api
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install luxwidget
```
If it is installed correctly, you should see something like this when you do `jupyter labextension list`
![image](https://user-images.githubusercontent.com/5554675/107362267-7ec01400-6b13-11eb-895d-63b86191f7eb.png)

Note that you may have to restart your JupyterLab server for the installed widget to show up.

**Comment by Winnergy** [comment]
Hi Doris,

You were right, the luxwidget is not installed properly as jupyterlab
extensions list reports errors about node.js and npm installation.
I tried to play around but then I have got errors about the Python version.
After updating Python version, I have got errors saying that some
pre-requisites cannot run on Win32 platform.

I wonder if it wouldn't be better to uninstall Anaconda and reinstall it
again with Jupyter, R, Orange, Spyder etc... and then add the lux library?
What do you think?

Kind Regards,
Catalin

**Comment by cjachekang** [comment]
Hi @Winnergy , we recently pushed out an update to put Lux on conda-forge, which could help with known issues with conda and lux. Could you try out the conda install and see if that works using `conda install -c conda-forge lux-api`. In any case, I am also currently working on getting Jupyter Lab 3 compatible with Lux, so using notebooks for now would be more stable. Let us know how it goes and feel free to reopen this issue if you still get the errors!
