### ISSUE TITLE
Binned charts should provide start, end, and step

### ISSUE THREAD

**Issue by domoritz** [lux-org/lux#265]
To make sure that Vega-Lite can render histograms correctly, Lux should provide the start and end of a bin as well as the step size. 

Here is an example of a simple bar chart. 

```py
df = pd.DataFrame({'start': [1,2,3,4,5], 'end': [2,3,4,5,6], 'count': [12,52,76,21,32]})

alt.Chart(df).mark_bar().encode(
  x = alt.X('start', bin = alt.Bin(binned=True, step=1)),
  x2 = 'end',
  y = 'count'
)
```

With this core, the space between bars is small (as it should be in a histogram) and the axis ticks on the x axis are spaced like the bars.

<img width="459" alt="Screen Shot 2021-02-15 at 20 07 47" src="https://user-images.githubusercontent.com/589034/107984986-0c6d8a80-6f7e-11eb-9787-424303be0126.png">

Relevant code https://github.com/lux-org/lux/blob/b12bf54bce412071e171189b7156bbb03a4e302f/lux/vislib/altair/Histogram.py#L66

After this fix, I think you can delete https://github.com/lux-org/lux/blob/b12bf54bce412071e171189b7156bbb03a4e302f/lux/vislib/altair/Histogram.py#L55.

**Comment by dorisjlee** [comment]
Thanks for the tip @domoritz! I think this might help with #217, we'll definitely look into this!

**Comment by domoritz** [comment]
Excellent. Happy to help if any questions come up.

**Comment by micahtyong** [comment]
Hi @domoritz! I've just opened up a [PR](https://github.com/lux-org/lux/pull/285) that takes your advice from this issue. Feel free to take a look and/or comment on the result!
