### ISSUE TITLE
Pull usage metrics and check availability of events

### ISSUE THREAD

**Issue by sophiahhuang** [lux-org/lux#274]
Lux Metrics:
https://github.com/lux-org/lux-logger/blob/master/INFO.md

On an individual or session level,
initWidget
exportBtnClick
switchTab
ClickVis
- Is there Intent tracking, of all users who started Lux?
- Is there time stamp between start/end? Start of an session and timed out/inactive states

**Comment by dorisjlee** [comment]
Closing this for now.
