### ISSUE TITLE
Dead Slack Invite Link

### ISSUE THREAD

**Issue by noklam** [lux-org/lux#316]
**Describe the bug**
https://lux-project.slack.com/join/shared_invite/zt-lilu4e87-TM4EDTq9HWzlDRycFsrkLg

The link is dead, I wanna join the slack group.

**Comment by dorisjlee** [comment]
Hi @noklam, Thanks for letting us know about the broken Slack invite link! I've just updated the [Slack invite link](https://communityinviter.com/apps/lux-project/lux). Please let me know if you are still experiencing issues with accessing the Slack group!

**Comment by noklam** [comment]
Cool! works now.

**Comment by noklam** [comment]
Actually I do not receive any invite link after putting my email. Try to re-register and it said this email is registered already.

**Comment by dorisjlee** [comment]
I just approved your invite request, you should get an invite link in your email now!
