### ISSUE TITLE
How to use lux library in Streamlit

### ISSUE THREAD

**Issue by arjunko** [lux-org/lux#324]
Hello, I’m not able to use the lux library streamlit. can you guide me on how do I use the lux library?   Note: lux library works on jupyter notebook .ipynb file but my code works on .py file.

Documentation and examples:   https://streamlit.io/

I used the below code but I can see only Dataframe. Visualizations are not showing.

import streamlit as st
import pandas as pd
import lux

def app():
    st.title('Generate EDA')
    st.write('Training Data Exploratory Data Analysis ')
    df = pd.read_csv(r'C:\Desktop\adult.csv')
    st.dataframe(df)
app()

**Comment by micahtyong** [comment]
Hi @arjunko, Lux is natively rendered as a widget for `.ipynb` files. That being said, for your specific use case, you can [export the Lux widget to an HTML file](https://lux-api.readthedocs.io/en/latest/source/guide/export.html#exporting-widget-visualizations-as-static-html) then render a [Streamlit Component](https://docs.streamlit.io/en/stable/streamlit_components.html). I've modified your code to be the following: 

```
import streamlit as st
import streamlit.components.v1 as components
from pathlib import Path
import pandas as pd
import lux

def app():
    st.title('Generate EDA')
    st.write('Training Data Exploratory Data Analysis ')
    df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")
    export_file = 'visualizations.html'
    df.save_as_html(export_file)
    txt = Path(export_file).read_text()
    components.html(txt, width=800, height=350)

app()
```

This outputs the following result as an interactive widget:
<img width="761" alt="Screen Shot 2021-03-26 at 12 35 20 PM" src="https://user-images.githubusercontent.com/44735047/112684376-309b7180-8e30-11eb-875d-e18d331fd8b6.png">

**Comment by arjunko** [comment]
@micahtyong Thank you for the help. When I ran the same code I'm getting the error as : 
AttributeError: 'DataFrame' object has no attribute 'save_as_html'
HTML page is not created. please help with this issue.

**Comment by dorisjlee** [comment]
See: #341

**Comment by arjunko** [comment]
@dorisjlee Thank you for the quick response. I'm running my script is in .py file not in jupyter notebook. when I use dataframe df by default it's consider as a pandas dataframe and when I ran above script I'm getting AttributeError: 'DataFrame' object has no attribute 'save_as_html'. please clarify help on this error code.

**Comment by djswoosh** [comment]
@dorisjlee is this same method replicable with streamlit in the cloud, I have been trying to do this without success yet. Code below.


with correlation:
	def app():
		st.title('Correlation')
		st.write('Check out these correlation charts')
		df = pd.read_csv('swooshstreams.csv', header =0)
		export_file = 'swooshstreams.html'
		html_content = df.save_as_html(output=True)
		components.html(html_content, width=800, height=350)

	app()

**Comment by dorisjlee** [comment]
Hi @djswoosh, We have not tried this on Streamlit Cloud, but it should be the same. Can you try the standalone code snippet and see if it works?
```python
import streamlit as st
import streamlit.components.v1 as components
from pathlib import Path
import pandas as pd
import lux

def app():
    st.title('Generate EDA')
    st.write('Training Data Exploratory Data Analysis ')
    df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")
    export_file = 'visualizations.html'
    df.save_as_html(export_file)
    txt = Path(export_file).read_text()
    components.html(txt, width=800, height=350)

app()
```

**Comment by djswoosh** [comment]
Hey @dorisjlee , I gave it a go, but this was the error message on the cloud app...


File "/home/appuser/venv/lib/python3.7/site-packages/streamlit/script_runner.py", line 354, in _run_script
    exec(code, module.__dict__)
File "/app/music-recommendation-engine-using-fma-dataset/sampleap.py", line 16, in <module>
    app()
File "/app/music-recommendation-engine-using-fma-dataset/sampleap.py", line 12, in app
    df.save_as_html(export_file)
File "/home/appuser/venv/lib/python3.7/site-packages/pandas/core/generic.py", line 5465, in __getattr__
    return object.__getattribute__(self, name)

**Comment by micahtyong** [comment]
Hi @djswoosh. I gave your code a go on Streamlit Cloud and reproduced the same error ([source code](https://github.com/micahtyong/lux-streamlit)). It looks like Streamlit Cloud fails to recognize Lux's Dataframe API when calling `save_as_html`, even if we include a `requirements.txt` in the source code. I've [opened an issue](https://discuss.streamlit.io/t/lux-and-streamlit-cloud-compatibility/21094) on Streamlit's discussion forum and will update you once I have a solution. Thanks for your patience.
