### ISSUE TITLE
Lux Installed correctly but wont produce visualizations

### ISSUE THREAD

**Issue by amyforza** [lux-org/lux#338]
**Describe the bug**
Lux installed but the Toggle/Pandas/Lux bottom does not produce visualizations as seen in screen shot.

**Screenshots**
![Screen Shot 2021-04-02 at 1 08 29 PM](https://user-images.githubusercontent.com/52613016/113437442-9352b700-93b4-11eb-9d8f-b04ccbad3a00.png)

**Comment by dorisjlee** [comment]
Hi @amyforza, Thanks for giving Lux a try! It looks like you are using Jupyter notebooks. I noticed that you seem to have a PermissionError at the top when you likely have ran:`jupyter nbextension install --py luxwidget`. In that case, you would have to add the `--user` flag: `jupyter nbextension enable --py --user luxwidget`

After installing, you may also want to restart your jupyter lab or notebook server to reload the widget. If you are still having problems with the widget display, please check out our [troubleshooting tips](https://lux-api.readthedocs.io/en/latest/source/guide/FAQ.html#troubleshooting-tips). Let us know if this fixes the problem for you!

**Comment by amyforza** [comment]
Hello and thank you for the response. I tried this but the command prompt is giving my the following issue:
"ambiguous option: --py (--pypi-url, --python-version?)"
I've searched online for what this means but cant find anything.
 



Thank you for the help


V/r,

Amy Forza
253-683-0323


 
    On Saturday, April 3, 2021, 07:48:06 PM EDT, Doris Lee ***@***.***> wrote:  
 
 


Hi @amyforza, Thanks for giving Lux a try! It looks like you are using Jupyter notebooks. I noticed that you seem to have a PermissionError at the top when you likely have ran:jupyter nbextension install --py luxwidget. In that case, you would have to add the --user flag: jupyter nbextension enable --py --user luxwidget

After installing, you may also want to restart your jupyter lab or notebook server to reload the widget. If you are still having problems with the widget display, please check out our troubleshooting tips. Let us know if this fixes the problem for you!

**Comment by amyforza** [comment]
Oh never mind, it looks like Lux is running in my notebook now and thank you!

V/r,
Amy Forza

    On Sunday, April 4, 2021, 08:28:36 AM EDT, Amy Forza ***@***.***> wrote:  
 
  
Hello and thank you for the response. I tried this but the command prompt is giving my the following issue:
"ambiguous option: --py (--pypi-url, --python-version?)"
I've searched online for what this means but cant find anything.
 



Thank you for the help


V/r,

Amy Forza
253-683-0323


 
    On Saturday, April 3, 2021, 07:48:06 PM EDT, Doris Lee ***@***.***> wrote:  
 
 


Hi @amyforza, Thanks for giving Lux a try! It looks like you are using Jupyter notebooks. I noticed that you seem to have a PermissionError at the top when you likely have ran:jupyter nbextension install --py luxwidget. In that case, you would have to add the --user flag: jupyter nbextension enable --py --user luxwidget

After installing, you may also want to restart your jupyter lab or notebook server to reload the widget. If you are still having problems with the widget display, please check out our troubleshooting tips. Let us know if this fixes the problem for you!

**Comment by dorisjlee** [comment]
Hi @amyforza, Glad to hear that it's working for you now! Closing this issue now, but feel free to start a new issue if you have any other questions!

**Comment by krishnaap** [comment]
> Hi @amyforza, Thanks for giving Lux a try! It looks like you are using Jupyter notebooks. I noticed that you seem to have a PermissionError at the top when you likely have ran:`jupyter nbextension install --py luxwidget`. In that case, you would have to add the `--user` flag: `jupyter nbextension enable --py --user luxwidget`
> 
> After installing, you may also want to restart your jupyter lab or notebook server to reload the widget. If you are still having problems with the widget display, please check out our [troubleshooting tips](https://lux-api.readthedocs.io/en/latest/source/guide/FAQ.html#troubleshooting-tips). Let us know if this fixes the problem for you!

how to enable it on jupyter-notebook, I mean how ? I tried to copy-paste the 
jupyter nbextension install --py luxwidget
on terminal but it wasn't working.

**Comment by dorisjlee** [comment]
Hi @krishnaap, Thanks for your question, to enable Lux for Jupyter notebook, you can run: 
```
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
If you are using Jupyter Lab, you would need to do: 
```
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install luxwidget
```
