### ISSUE TITLE
[BUG] The extension "luxwidget" does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by ginodanimal** [lux-org/lux#339]
**Describe the bug**
After following installation instructions for Jupyter lab from [here](https://lux-api.readthedocs.io/en/latest/source/getting_started/installation.html), the following error occurs from the last jupyter lab extension install command:

'(py38)'C:\Users\gino_>jupyter labextension install luxwidget
C:\Users\gino_\anaconda3\envs\py38\lib\site-packages\jupyter_server\transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
An error occured.
**ValueError: The extension "luxwidget" does not yet support the current version of JupyterLab**.

**To Reproduce**
1. Using Jupyter Lab 3.0.12 follow installation instructions  [here](https://lux-api.readthedocs.io/en/latest/source/getting_started/installation.html),

2. See error from "jupyter labextension install luxwidget" command:
... An error occured.
ValueError: The extension "luxwidget" does not yet support the current version of JupyterLab.

**Expected behavior**
Known nbextensions:  would show luxwidget for my Virtual Environment, not base VE.

'(py38)'C:\Users\gino_>jupyter nbextension list
Known nbextensions:
  config dir: C:\Users\gino_\.jupyter\nbconfig
    notebook section
      luxwidget/extension enabled
      - Validating: ok
  config dir: C:\Users\gino_\anaconda3\envs\py38\etc\jupyter\nbconfig
    notebook section
      jupyter_dash/main enabled
      - Validating: ok
      plotlywidget/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok

**Screenshots**
Jupyter Lab Version:
![Jlab_Ver](https://user-images.githubusercontent.com/17731281/113486723-37566400-9482-11eb-9673-417033a6e8ad.png)

**Comment by dorisjlee** [comment]
Hi @ginodanimal, Thank you for your interest! Lux currently does not currently support JupyterLab 3 ([lux-widget:#64](https://github.com/lux-org/lux-widget/issues/64)). We are working on adapting Lux to support JupyterLab 3 soon.

**Comment by dorisjlee** [comment]
Hi @ginodanimal, We now support Jupyter Lab 3 in our latest release of lux-api and lux-widget. You can upgrade and install it by running this in the command line:
```bash
pip install --upgrade lux-api lux-widget
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install luxwidget
```
Let us know if this works for you!

**Comment by ginodanimal** [comment]
WOW!  Nice  😉  Sent from Mail for Windows 10 From: Doris LeeSent: Tuesday, April 20, 2021 12:09 PMTo: lux-org/luxCc: ginodanimal; MentionSubject: Re: [lux-org/lux] [BUG] The extension "luxwidget" does not yet support the current version of JupyterLab. (#339) Hi @ginodanimal, We now support Jupyter Lab 3 in our latest release of lux-api and lux-widget. You can upgrade and install it by running this in the command line:pip install --upgrade lux-api lux-widgetjupyter labextension install @jupyter-widgets/jupyterlab-managerjupyter labextension install luxwidgetLet us know if this works for you!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
