### ISSUE TITLE
[BUG] How to convert <class 'pandas.core.frame.DataFrame'> to Lux dataframe

### ISSUE THREAD

**Issue by arjunko** [lux-org/lux#341]
Hello,
 Is there any method to explicitly convert pandas dataframe to lux dataframe.  Because when I'm trying to convert pandas dataframe df.save_to_html then pandas dataframe is not supporting. I'm getting error as : AttributeError: 'DataFrame' object has no attribute 'save_as_html'. 
Please help on this issue. Thank you.

**Comment by dorisjlee** [comment]
Hi @arjunko, Thanks for your question. To convert a Pandas dataframe to Lux Dataframe, you can do `lux.LuxDataFrame`
```python
df = lux.LuxDataFrame(pandas_df)
```
Although generally, all dataframes after you `import lux` at the top of your notebook should be a LuxDataFrame. Could you explain what was the series of pandas commands you did that might have led to a Pandas dataframe? It would help us with debugging Lux for future uses. Thanks!

**Comment by arjunko** [comment]
@dorisjlee Thank you for the quick response. I'm running my script is in .py file not in jupyter notebook. when I use dataframe df by default it's consider as a pandas dataframe and when I ran below script I'm getting AttributeError: 'DataFrame' object has no attribute 'save_as_html'. please clarify help on this error code.

import streamlit as st
import streamlit.components.v1 as components
from pathlib import Path
import pandas as pd
import lux

def app():
    st.title('Generate EDA')
    st.write('Training Data Exploratory Data Analysis ')
    df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")
    export_file = 'visualizations.html'
    df.save_as_html(export_file)
    txt = Path(export_file).read_text()
    components.html(txt, width=800, height=350)

app()
