### ISSUE TITLE
Toggle pandas/lux not working[BUG]

### ISSUE THREAD

**Issue by Amarnath-17** [lux-org/lux#344]
**Describe the bug**
I have installed lux and validated the extension in jupyter notebook

C:\Users\AmarnathMohan>jupyter nbextension enable --py luxwidget
Enabling notebook extension luxwidget/extension...
      - Validating: ok

after reading the csv file in notebook, the toggle button appears but clicking on that is not displaying any visualizations.

**To Reproduce**
Please describe the steps needed to reproduce the behavior. For example:

**Expected behavior**

**Screenshots**

**Additional context**

![image](https://user-images.githubusercontent.com/68593493/113875248-2edc9100-97d4-11eb-9273-fa29fa05121d.png)

**Comment by dorisjlee** [comment]
Hi @Amarnath-17, Thanks for the question! It looks like you are using Jupyter notebook? After installing, you may also want to restart your Jupyter notebook server to reload the widget. If you are still having problems with the widget display, please check out our [troubleshooting tips](https://lux-api.readthedocs.io/en/latest/source/guide/FAQ.html#troubleshooting-tips). Let us know if this fixes the problem for you!

**Comment by Amarnath-17** [comment]
Hello Doris,

Thanks a lot. Restarting the kernel and jupyter notebook solved the issue.

**Comment by dorisjlee** [comment]
Great, I'm glad that solved the issue for you!
