### ISSUE TITLE
How to run lux library in .py file and how to create result in html

### ISSUE THREAD

**Issue by arjunko** [lux-org/lux#345]
Hello, I'm importing lux library and running script in ****.py**** file but I'm unable to generate the visualization. when I use data frame(df) by default it's considered as a pandas data frame, not a lux data frame. Also can you help me when I'm trying to save in HTML file then I got error as AttributeError: 'DataFrame' object has no attribute 'save_as_html'. 

from pathlib import Path
import pandas as pd
import lux

def app():
   df = pd.read_csv(r"C:\Users\adult.csv")
  export_file = 'visualizations.html'
  df.save_as_html(export_file)
  txt = Path(export_file).read_text()
app()

**Comment by micahtyong** [comment]
Hi @arjunko, is this in regards to the Streamlit library? Like I mentioned in #324, you'll have to use Streamlit components to render the Lux widget in HTML. In your case, 

```
import streamlit.components.v1 as components

def app():
    df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")
    export_file = 'visualizations.html'
    df.save_as_html(export_file)
    txt = Path(export_file).read_text()
    components.html(txt, width=800, height=350) # this is where we render the widget! 

app()
```

With regards to the error you're getting, what installation steps did you take and what Python version are you running? Consider joining our [Slack] as well if you'd like some more guidance.

**Comment by dorisjlee** [comment]
Hi @arjunko, Closing this for now, but let us know if you are still running into any issues!
