### ISSUE TITLE
[BUG] `lux.LuxDataFrame(df)` not working as intended

### ISSUE THREAD

**Issue by westernguy2** [lux-org/lux#367]
**Describe the bug**
Pandas `DataFrame` is able to make a copy of the DataFrame by calling `pd.DataFrame(df)`. This is not the case for `LuxDataFrame`.

**To Reproduce**
I encountered this error using the following code:

```python
import pandas._testing as tm
df = tm.makeDataFrame()
lux.LuxDataFrame(df)
```
The output DataFrame is

![Screen Shot 2021-04-21 at 3 40 00 PM](https://user-images.githubusercontent.com/32151899/115629770-d7502200-a2b7-11eb-8340-af3bbbab7224.png)

while it should be showing up as 
 
![Screen Shot 2021-04-21 at 3 39 40 PM](https://user-images.githubusercontent.com/32151899/115629727-cbfcf680-a2b7-11eb-9521-aa13880511c4.png)

This bug doesn't happen in all cases, only some cases. For example

```python
df = pd.read_csv('lux/data/car.csv')
lux.LuxDataFrame(df)
```

works as expected.

**Comment by dorisjlee** [comment]
Thanks for report this issue @westernguy2! Do you think this might be a result of the index column not being the typical ordered IntIndex, but something that looks like a result of `set_index` called on a column?

**Comment by westernguy2** [comment]
Yes, that is probably the reason this is happening, since that seems to be the main difference between the two examples. I will take a closer look at the index, thanks!
