### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sherzod-az** [lux-org/lux#371]
C:\Users\Sherzod Azamov\anaconda3\lib\site-packages\IPython\core\formatters.py:345: UserWarning:
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.
![image](https://user-images.githubusercontent.com/83573146/116849637-8bcb3b80-ac08-11eb-98ff-9c08dd0bdcc7.png)

**Comment by dorisjlee** [comment]
Thanks for reporting this issue @sherzod-az! Could you let us know what dataset and commands you used that lead to this error? This can help us reproduce and debug the issue.

**Comment by dorisjlee** [comment]
Hi @sherzod-az, It seems like this issue could possibly be stemming from an older version of Lux. You could try upgrading to the latest version of Lux to see if it might help resolve this issue.
```
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
I'll close this issue for now, but feel free to reopen this or start a new issue if you are still running into issues!
