### ISSUE TITLE
How do you export the underlying means data from the chart vislist?

### ISSUE THREAD

**Issue by Josephsmurph13** [lux-org/lux#383]
from lux.vis.VisList import VisList
vc = VisList(["Target","?"],df)
vc

print(VisList(["Target","?"],df))

When you print it just gives you the target variable and the other feature variable. I am looking to extract the mean of the target for the various categorial values within this feature variable? 

I have tried print (vc.to_matplotlib()) but this doesn't appear to work.

Any help would be much appreciated.

Kind regards 
Joe

**Comment by dorisjlee** [comment]
Hi @Josephsmurph13,
Thanks for your question! I'm glad that you are finding the `VisList` useful, it is a very convenient way to work with lots of visualizations at once! 

When you are working with the `VisList`, it is a list of visualization, if you are interested in fetching the data values (e.g. mean expressed by the bar chart), or converting it into matplotlib, you would need to access the `Vis` element in your `VisList`, like `barchart = vc[1]` for the second `Vis` in your `VisList`. 

```python
df = pd.read_csv("https://github.com/lux-org/lux-datasets/blob/master/data/hpi_full.csv?raw=True")
from lux.vis.VisList import VisList
vc = VisList(["AvrgLifeExpectancy","?"], df)
barchart = vc[1]
```

![Screen Shot 2021-06-17 at 7 18 58 PM](https://user-images.githubusercontent.com/5554675/122496588-e0e8c400-cfa0-11eb-9f1b-f4a49e46edef.png)

To fetch the data itself, you can use the `.data` property. You can also call `.to_matplotlib()` on the `Vis` to get the matplotlib code.

```python
barchart.data

print(barchart.to_matplotlib())
```

<img src="https://user-images.githubusercontent.com/5554675/122496654-f958de80-cfa0-11eb-9d4a-ada7a9fd4671.png" width="200px"></img>

Let me know if that answers your question!

**Comment by Josephsmurph13** [comment]
Hi @Doris ***@***.***>,

Thank you very much for you quick response. The instructions below do exactly what I want. I see, you have to extract each charts data individually and not in a list (VisList).

I am very new to Python and am really impressed with Lux as a means of quickly visualising data relationships.

Kind regards,
Joe

Joseph Murphy
Senior Consultant
Direct : +44 113 306 1594 | Mobile : +44 7733 013 876 | ***@***.******@***.***>

[test]<http://www.gmap.com/>
GMAP Analytics Ltd | www.gmap.com<http://www.gmap.com/> | GMAP Analytics, Nexus - University of Leeds, Discovery Way, Leeds, LS2 3AA, United Kingdom [LI-In-Bug] <http://www.linkedin.com/company/gmap-analytics>

**Comment by dorisjlee** [comment]
Hi @Josephsmurph13, Glad to hear that you're finding Lux useful! Feel free to let us know if you run into any other questions!

**Comment by Josephsmurph13** [comment]
Hi,

I have got a new laptop and am trying to toggle to lux from panda but can't get the charts to show

***@***.***

I have run the below so far. Please could you kindly advise how I get the charts to show? Lux is a great tool but just can't get it to work atm?


pip uninstall lux-api

pip uninstall lux-widget



jupyter nbextension uninstall --py luxWidget

jupyter nbextension disable --py luxWidget



pip install lux-api



jupyter nbextension install --py luxwidget

jupyter nbextension enable --py luxwidget

jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyter-matplotlib

Kind regards,
Joe

Joseph Murphy
Senior Consultant
***@***.******@***.***>

[test]<http://www.gmap.com/>
GMAP Analytics Ltd | www.gmap.com<http://www.gmap.com> |  | GMAP Analytics, Nexus - University of Leeds, Discovery Way, Leeds, LS2 3AA, United Kingdom [LI-In-Bug] <http://www.linkedin.com/company/gmap-analytics>

From: Joseph Murphy
Sent: 18 June 2021 09:50
To: lux-org/lux ***@***.***>; lux-org/lux ***@***.***>; Doris Lee ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [lux-org/lux] How do you export the underlying means data from the chart vislist? (#383)

Hi @Doris ***@***.***>,

Thank you very much for you quick response. The instructions below do exactly what I want. I see, you have to extract each charts data individually and not in a list (VisList).

I am very new to Python and am really impressed with Lux as a means of quickly visualising data relationships.

Kind regards,
Joe

Joseph Murphy
Senior Consultant
Direct : +44 113 306 1594 | Mobile : +44 7733 013 876 | ***@***.******@***.***>

[test]<http://www.gmap.com/>
GMAP Analytics Ltd | www.gmap.com<http://www.gmap.com/> | GMAP Analytics, Nexus - University of Leeds, Discovery Way, Leeds, LS2 3AA, United Kingdom [LI-In-Bug] <http://www.linkedin.com/company/gmap-analytics>

**Comment by dorisjlee** [comment]
Hi @Josephsmurph13, Could you open a [new issue](https://github.com/lux-org/lux/issues/new/choose) describing the problem that you're seeing? It would also be great to describe whether you are using Jupyter Notebook or Jupyter Lab, as well as what error message or screenshot of display you are seeing after you run the following example in your notebook: 
```python
import lux
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df
```
Thanks again and we're excited to hear that you're continuing to use Lux!

**Comment by Josephsmurph13** [comment]
Hi Doris,

I have sorted the issue by uninstalling Lux and jupyter lab. This appears to have fixed it. Thanks for getting back to me so quickly.

Kind regards,
Joe

Joseph Murphy
Senior Consultant
***@***.******@***.***>

[test]<http://www.gmap.com/>
GMAP Analytics Ltd | www.gmap.com<http://www.gmap.com> |  | GMAP Analytics, Nexus - University of Leeds, Discovery Way, Leeds, LS2 3AA, United Kingdom [LI-In-Bug] <http://www.linkedin.com/company/gmap-analytics>
