### ISSUE TITLE
Describe how to include Lux in a Panel App

### ISSUE THREAD

**Issue by MarcSkovMadsen** [lux-org/lux#384]
## Problem

I am a user of and contributor to [Panel](https://panel.holoviz.org/). I would like it to be easy for Panel users to add `Lux` into the mix for interactive data exploration or building tools and apps.

Currently it's not frictionless as the html of Lux needs to be wrapped into an iframe to be used with a `panel.pane.HTML` pane.

## Solution

Add a description of how to combine Lux and Panel to the documentation.

### Exporting to Panel

[Panel][] is a powerful Python library for interactive data exploration and data apps. To integrate Lux with Panel, you can wrap the HTML widget output with a [panel.pane.HTML][] pane as shown below:

``` python
import html

import pandas as pd
import panel as pn
import lux

pn.extension(sizing_mode="stretch_width")

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")

def to_lux_panel(df, style="width:100%;height:100%", frameborder="0"):
    html_content = df.save_as_html(output=True)
    html_content = html.escape(html_content)
    iframe_report = f"""<iframe srcdoc="{html_content}" style={style} frameborder="{frameborder}"
"allowfullscreen></iframe>"""

    return pn.pane.HTML(iframe_report, height=425)

# Can display in notebook
lux_panel = to_lux_panel(df)

# Can display as app with panel serve
pn.template.FastListTemplate(title="💡 Lux meets Panel", main=[lux_panel]).servable();
```

After running `panel serve app.ipynb` or `panel serve app.py` in the command line, you should find the Panel app hosted in your browser (e.g., `http://localhost:5006/app`):

  [Panel]: https://panel.holoviz.org/
  [panel.pane.HTML]: https://panel.holoviz.org/reference/panes/HTML.html

![lux-panel](https://user-images.githubusercontent.com/42288570/122703636-55965980-d252-11eb-9152-38a9df44214d.png)

## Additional Context

Checkout my site [awesome-panel](https://awesome-panel.org) or hook up on on twitter [@MarcSkovMadsen](https://twitter.com/MarcSkovMadsen) if you want to see what Panel is capable of.

**Comment by dorisjlee** [comment]
Merged #385, thanks @MarcSkovMadsen!
