### ISSUE TITLE
save_as_html raises Object of type int64 is not JSON serializable

### ISSUE THREAD

**Issue by MarcSkovMadsen** [lux-org/lux#393]
I'm trying to add a Lux app to my site awesome-panel.org based on https://lux-api.readthedocs.io/en/latest/source/guide/export.html?highlight=panel#exporting-to-panel

When I run the below inside my ` python:3.7.4-slim-stretch` based docker container

```python
import pandas as pd
import lux

df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/hpi.csv")
df.save_as_html(output=True)
```

I get

```bash
root@5ed63fa380e7:/app# python 'application/pages/lux_app/__init__.py'
Traceback (most recent call last):
  File "application/pages/lux_app/__init__.py", line 5, in <module>
    df.save_as_html(output=True)
  File "/usr/local/lib/python3.7/site-packages/lux/core/frame.py", line 772, in save_as_html
    manager_state = json.dumps(data["manager_state"])
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type int64 is not JSON serializable
```

I'm using 

python: 3.7.4
lux-widget: 0.1.5
lux-api: 0.3.1
numpy: 1.19.5
pandas: 1.2.2

**Comment by dorisjlee** [comment]
Hi @MarcSkovMadsen, I tested this on both lux-widget 0.1.5 and 0.1.6, but I can't seem to be able to reproduce this error. If you are still seeing this issue, let me know if there is something specific that might be causing this issue (e.g., code running inside a larger script).

**Comment by dorisjlee** [comment]
Closing this for now, let us know if you are still having issues with this! Thanks!
