### ISSUE TITLE
Are Binder examples working?

### ISSUE THREAD

**Issue by michaelaye** [lux-org/lux#399]
In both Safari and Brave on iPad, and Firefox on Desktop, when I click on the Toggle pandas/lux button, all that happens is that the cell output is toggled away, no lux plots appear. Thinking it might be slower execution on Binder, I waited 2 minutes for something to appear, but nothing happened. I also tried the 2nd gallery example with the same issue. No errors shown either.

**Comment by dorisjlee** [comment]
Hi @michaelaye, Thank you for reporting this issue. Lux currently only support Chrome for Desktop, we have not tested this extensively for other browsers like Firefox or Safari. Let us know if it works if you try this on Chrome.

**Comment by michaelaye** [comment]
I didn't see that in the README, will try on Chrome.

**Comment by michaelaye** [comment]
ugh, not even Chromium? It has to be Chrome?

**Comment by michaelaye** [comment]
Tried Chromium, Brave, and Chrome now, still not working, no other plots appear when I click toggle in cell [4].
This is what I'm trying:
https://hub.gke2.mybinder.org/user/lux-org-lux-binder-6ctrukf7/notebooks/demo/cars_demo.ipynb

**Comment by dorisjlee** [comment]
Ah I see, it looks like the Jupyter Notebook link is not working (related to #372).
Could you please try [this Binder link](https://mybinder.org/v2/gh/lux-org/lux-binder/master?urlpath=lab/tree/demo/cars_demo.ipynb) for the JupyterLab version instead? Let me know if you are still seeing issues with this. Thanks!

**Comment by michaelaye** [comment]
I'm getting this error shown:

FileNotFoundError: Could not find package.json under dir /srv/conda/envs/notebook/lib/python3.7/site-packages/luxwidget

![image](https://user-images.githubusercontent.com/69774/125133447-1fb2fb00-e0c3-11eb-9968-eb78f19701fd.png)

**Comment by michaelaye** [comment]
at the end the JLab was actually loading. But led me to the next thing not working (new issue).

**Comment by dorisjlee** [comment]
Thanks for reporting this. You're right that this seems like the same issue as #372. Closing this for now, but we will look into resolving issue #372 soon!
