### ISSUE TITLE
Missing the tabs Distribution and Correlation in the widget

### ISSUE THREAD

**Issue by mona950101** [lux-org/lux#400]
Hi there,

I've installed lux wth our internal Jupyter platform with the following command:
```
pip install lux-api
jupyter nbextension install luxwidget --py --symlink --sys-prefix
jupyter nbextension enable luxwidget --py --sys-prefix
```

But when I test it in the notebook with the dataset **_college.csv_**, only one tab Occurrence is there, the other two **_Distribution_** and **_Correlation_**  are missing. I've attached the image as follows:
![Screen Shot 2021-07-07 at 3 46 41 PM](https://user-images.githubusercontent.com/80719086/124827249-6ece2400-df3b-11eb-983c-a0926b7fadcd.png)

The only error I see from the console is:
`Error: Host is not attached.`

I'm using:
```
Python 3.6
Lux 0.2.3
Pandas 1.1.2
```

Does anyone know how to fix that or could you please point me to the correct place to debug? 
Thanks a lot!

**Comment by dorisjlee** [comment]
Hi @mona950101, Thank you for reporting the issue! From your screenshot, it seems like the columns in the dataset are parsed incorrectly as categorical variables. It looks like the column names are also different from the original column name in the college dataset. I'm wondering if there are some specific data operations that you did to the dataframe before printing it out.
Could you try this code below to see if you are able to see the rest of the tabs? 
```python
import pandas as pd
import lux
df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df
```
<img width="1007" alt="Screen Shot 2021-07-09 at 6 51 09 AM" src="https://user-images.githubusercontent.com/5554675/125088187-0d649d00-e082-11eb-9379-b4eea4435b43.png">

**Comment by dorisjlee** [comment]
Closing this for now, let us know if you run into any other questions @mona950101!
