### ISSUE TITLE
UserWarning: Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.[BUG]

### ISSUE THREAD

**Issue by Suman-hulk** [lux-org/lux#406]
**Describe the bug**

**To Reproduce**
Please describe the steps needed to reproduce the behavior. For example:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dorisjlee** [comment]
Hi @Suman-hulk, Welcome to the Lux Github issues pages. Please provide a description of how to reproduce the issue that you are seeing, so we can help you debug the problem!

**Comment by Suman-hulk** [comment]
Problem solved. No problem.

**Comment by dorisjlee** [comment]
That's great to hear @Suman-hulk !
