### ISSUE TITLE
[BUG] Lux showing only max 10 values on x-axis. How to increase it?

### ISSUE THREAD

**Issue by SnowRipple** [lux-org/lux#408]
Sorry, not sure if this is a bug, but I cannot find the information anywhere.

When visualizing more than 10 values I get (" + X more ...") in the top right corner but I cannot "unroll it". Seems like Lux is limited to just 10 values on X-axis, how do it increase this limit?

**Comment by dorisjlee** [comment]
Hi @SnowRipple, We have added an additional configuration to change this default. See [these docs for more details](https://lux-api.readthedocs.io/en/latest/source/reference/config.html#change-the-maximum-number-of-bars-displayed). This will be updated along with our next release, thanks!
