### ISSUE TITLE
[BUG] Lux in VScode causes problems with memory resources

### ISSUE THREAD

**Issue by flight505** [lux-org/lux#413]
**Describe the bug**
Loading 3-4 widgets in VScode seems to causes problems with memory resources. 
I tested the same notebook in jupyter lab without issues. 
Does anyone else have the same issues? 

----- 
Also - it would be nice to close the lux widgets after use. for example a quick way to get and embed png's for saving notebooks. Currently, the fastest way seems to-be right-click on the graphs and then save them and use PLI to import and display them back in the notebook.
But that is not great and also doesn't work for VScode.

**Comment by dorisjlee** [comment]
Thanks for reporting this issue @flight505! 
It seems like this issue is worse in VSCode than it is in JupyterLab. We can look into doing some memory profiling to see what is happening here. Related #369.

**Comment by flight505** [comment]
Changed to Vscode insiders solved the issue for me.

**Comment by dorisjlee** [comment]
Hmm interesting, thanks for letting us know!
