### ISSUE TITLE
[BUG] Bin Determination Edge Case

### ISSUE THREAD

**Issue by dorisjlee** [lux-org/lux#415]
**Describe the bug**

In the college dataset, there are only 23 rows where HighestDegree='Associate', as a result, the bin size determined via the new formula (#302) is incorrect. 

**To Reproduce**

```python
import lux
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/lux-org/lux-datasets/master/data/college.csv")
df.intent = ["SATAverage","HighestDegree=Graduate"]
df
```
![Screen Shot 2021-08-26 at 4 29 56 PM](https://user-images.githubusercontent.com/5554675/131048799-4d2c5dd9-0289-49f2-a654-dae76a00114e.png)

**Comment by micahtyong** [comment]
Hi @dorisjlee, I found some time to play around with the college dataset to address this edge case. The new chart is displayed below: 
![Screen Shot 2022-01-17 at 6 37 37 PM](https://user-images.githubusercontent.com/44735047/149861255-362c4844-9e19-4e28-ad59-84797d2dcb0d.png)
