### ISSUE TITLE
Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display.

### ISSUE THREAD

**Issue by nehadamele** [lux-org/lux#423]
RecursionError: maximum recursion depth exceeded while calling a Python object

```
import lux
import pandas as pd

# creating a Dataframe object 
df = pd.DataFrame(dict_country)
  
df
```

I am attaching the log messages; hopefully that might be helpful in following where the issue might be.
[error.log](https://github.com/lux-org/lux/files/7318396/error.log)

lux version: 0.4.0
panda version: 1.2.5

**Comment by dorisjlee** [comment]
Hi @nehadamele, Thanks for reporting this issue! Could you provide the dataset or a sample of the data `dict_country` that led to this error? This can help us debug and pinpoint why this error is showing up!

**Comment by Emmastro** [comment]
I was getting this error when I had a column with inconsistent data types. The column was supposed to be a Timestamp column but had a few integer values, so the column type was just of type object. Lux was trying to compare values from this column and raised the error: ```TypeError: '<' not supported between instances of 'Timestamp' and 'int'``` then fall back to the default pandas table

**Comment by dani-lbnl** [comment]
Hi folks, different problem here: pd renders in lux, I can toggle, but it's not possible to scroll horizontally to see all the graphs - the arrow just does not work. Any thoughts?

**Comment by cgarciae** [comment]
Looked into this but I couldn't reproduce it with the [1-specifying-intent](https://github.com/lux-org/lux-binder/blob/master/tutorial/1-specifying-intent.ipynb) notebook as suggested by @dani-lbnl.

**Comment by dani-lbnl** [comment]
yeap,  @cgarciae, problem persists, thoughts?

**Comment by labanyamukhopadhyay** [comment]
Hi @dani-lbnl, when clicking into the right side of the widget are you not able to scroll/ see a scrollbar like the one below? You could try running `pip install --upgrade lux-api` in your terminal and then run lux in your Jupyter Notebook

<img width="988" alt="Screen Shot 2022-03-21 at 1 55 58 AM" src="https://user-images.githubusercontent.com/17665008/159230492-0ab47ea1-31f6-4945-a875-1902965f9be9.png">

**Comment by tbnsilveira** [comment]
I faced the same problem today. Running `lux.debug_info()` showed versions lux 0.5.1 and pandas 1.2.5. Upgrading my pandas package to version 1.2.5 solved the issue.

**Comment by adrohan19** [comment]
I've been getting the same "Unexpected error in rendering Lux widget and recommendations. Falling back to Pandas display" issue. I upgraded pandas and Lux, and fixed any temporal issues, any idea what could be going wrong?

**Comment by dorisjlee** [comment]
Thanks for your question @adrohan19. The `Falling back to Pandas display` error can stem from many different issues. Could you create a separate issue with your code and data so that we can reproduce this issue? Thanks!
