### ISSUE TITLE
Failed to build pandas ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by gramamoo** [lux-org/lux#434]
"UNABLE TO INSTALL LUX-API. GET AN ERROR DURING INSTALLATION for Python 3.10.0: Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects"

**To Reproduce**
pip install lux-api

output:
Collecting lux-api
  Using cached lux_api-0.4.0-py3-none-any.whl
...
...
...
...
Building wheels for collected packages: pandas
  Building wheel for pandas (pyproject.toml) ... error
...
...
...
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for pandas
Failed to build pandas
ERROR: Could not build wheels for pandas, which is required to install pyproject.toml-based projects

**Comment by dorisjlee** [comment]
Hi @gramamoo, This seems to be a pandas-specific issue. Please refer to [this related issue](https://github.com/microsoft/vscode-python/issues/17760). Thanks!
