### ISSUE TITLE
Loading Lux library into StreamLit Cloud

### ISSUE THREAD

**Issue by djswoosh** [lux-org/lux#439]
**Is your feature request related to a problem? Please describe.**
Trying to deploy my data project with Lux visualisations in the streamlit cloud, but no idea what to put in the requirements.txt or packages.txt file so keep getting deployment errors.

**Describe the solution you'd like**
The ability to get lux working with streamlit cloud.

**Comment by cgarciae** [comment]
Hey! Put `lux-api`, this is described in the installation section of the readme.

**Comment by cgarciae** [comment]
Closing this for now. Feel free to open it if its still an issue.
