### ISSUE TITLE
[Feature Request] New Release

### ISSUE THREAD

**Issue by dhirschfeld** [lux-org/lux#443]
It would be great if a new release could be published which includes https://github.com/lux-org/lux/pull/428 and hence allows `lux` to be used with `pandas >=1.3`

**Comment by dorisjlee** [comment]
Thanks @dhirschfeld! We're aiming to make a release to include #428 and a few other bug fixes towards the end of this month!

**Comment by dorisjlee** [comment]
Hi @dhirschfeld! 
Thanks for your patience. We finally made a new release that incorporates #428. 
You can access these updated changes by upgrading to [the latest version of Lux](https://pypi.org/project/lux-api/):
```python
pip install --upgrade lux-api
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```
Let us know what you think!
