### ISSUE TITLE
[Feature Request] Compatibility with Microsoft Edge browser

### ISSUE THREAD

**Issue by zhixx018** [lux-org/lux#456]
I am trying to use lux in Jupyter notebook.
The API is installed using pip and validation is successful.
However, the toggle button does not show up, and so, I searched the document of lux.
it turns out that 

_'If you are able to import lux successfully and you do not see the “Toggle button” when you print the dataframe, it may be possible that Lux is not compatible with your browser. Lux is compatible with Google Chrome, but have not been extensively tested on Safari or Firefox'_

I am currently using Edge, and as such, it would be great if the compatibility issue could be fixed. Thanks.

**Comment by labanyamukhopadhyay** [comment]
Hi @zhixx018 thank you for reporting the issue! I tried out lux on Microsoft Edge and the toggle feature works for me. Have you already activated the Jupyter notebook extension by running the following in your terminal? 
```
jupyter nbextension install --py luxwidget
jupyter nbextension enable --py luxwidget
```

**Comment by zhixx018** [comment]
Yes, I ve been using Jupyter with other extensions on for a couple of years.

**Comment by labanyamukhopadhyay** [comment]
@zhixx018 You can use lux.debug_info() to see if any extensions have not been enabled. To use this you need to upgrade to the newest release of lux by running `pip install --upgrade lux-api` in your terminal and then in your Jupyter notebook:
``` python
import lux
lux.debug_info()
```
This should return a message regarding any installation issues with luxwidget.

**Comment by zhixx018** [comment]
@labanyamukhopadhyay 
Thank you for your detailed guide and it works.
It looks amazing!
