### ISSUE TITLE
[Feature Request] Could you please make dependency of `sh` optional ?

### ISSUE THREAD

**Issue by ivaquero** [lux-org/lux#464]
**Is your feature request related to a problem? Please describe.**
The conda build of `sh` does not have support for Windows or MacOS-Arm64.  As a Mac M1 user, I can not update `lux-api` to `0.5.*`. And `0.4.*` of `lux-api` limit `pandas` update.

**Describe the solution you'd like**

I hope dependency of `sh` can be optional or replace `sh` by alternative packages having noarch builds.

Since maintenance of `sh` is not in a very active status and its functionality is not complex, I guess it is not a bad idea for you to implement the same functions that you need on your own.

**Comment by dorisjlee** [comment]
Resolved this issue! This change is now available on the latest code in `master` on Github. It will also be added to our next release!

**Comment by ivaquero** [comment]
Thank you !
