### ISSUE TITLE
[BUG]  jupyter labextension install @jupyter-widgets/jupyterlab-manager  ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package

### ISSUE THREAD

**Issue by subu** [lux-org/lux#470]
jupyter labextension install @jupyter-widgets/jupyterlab-manager

opt/oss/conda3/lib/python3.7/site-packages/jupyter_client/channels.py:15: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  from .session import Session
An error occurred.
ValueError: "@jupyter-widgets/jupyterlab-manager" is not a valid npm package

**Comment by dorisjlee** [comment]
Thanks @subu. This looks like an error that is coming from jupyter, specifically jupyter extension, rather than from Lux. You may want to open an issue [here](https://github.com/jupyter/jupyter_client) instead.
