### ISSUE TITLE
[BUG] Pre-commit hooks check failing due to Black version

### ISSUE THREAD

**Issue by labanyamukhopadhyay** [lux-org/lux#471]
**Describe the bug**

Pre-commit check is failing due to new black update. This is causing `ImportError: cannot import name '_unicodefun' from 'click'`. Black version needs to be updated to 22.3.0 and click version should be pinned to <8.1.0.

**Comment by dorisjlee** [comment]
Merged #472. Thanks @labanyamukhopadhyay !
