### ISSUE TITLE
[BUG] Vscode opens new tab when toggling on lux tabs

### ISSUE THREAD

**Issue by stvgz** [lux-org/lux#477]
**Describe the bug**
 Vscode opens new tab when toggling on lux tabs "Correlation" or "Distribution".

**To Reproduce**
Please describe the steps needed to reproduce the behavior. For example:
1. Using this code to reproduce

```python 
# pip install lux-api
import lux
import pandas as pd
import sklearn.datasets as datasets

data = datasets.fetch_california_housing()
df = pd.DataFrame(data['data'],columns=data['feature_names'])
df[data['target_names'][0]] = data['target']

df.head()
```

2. Click on 'Toggle Pandas/Lux'
Everything looks fine

3. Click on  tabs

<img width="363" alt="image" src="https://user-images.githubusercontent.com/29873245/167594231-8d52189a-8be9-43d2-ba33-1307bdbced3b.png">

Vscode opens new tab and showed an error

<img width="443" alt="image" src="https://user-images.githubusercontent.com/29873245/167594235-06211439-6ff2-4de4-af2e-5020e00f1087.png">

vscode opens a new tab
<img width="279" alt="image" src="https://user-images.githubusercontent.com/29873245/167594232-8ea093fc-3553-4ea5-848e-ec101e27bf43.png">

**Additional context**
OS: 11.6.2 (20G314)
Python 3.7.13
lux-api              0.5.1
lux-widget           0.1.11
Vscode Version: 1.67.0 (Universal)

**Comment by dorisjlee** [comment]
Thanks for raising this issue @stvgz! I believe this is the same issue as what is reported in #96. I will close this issue for now and we will look into resolving #96.

**Comment by stvgz** [comment]
Thanks！ @dorisjlee
