### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by aguamentiPatronum** [lux-org/lux#479]
**Describe the bug**
Using the toggle button in a Jupyter Notebook in Chrome causes error "Uncaught (in promise) Error: Host is not attached." This impacts the ability to programmatically manipulate the notebook after the error arises. Perhaps requires [de]serialization of subwidgets, as mentioned in low-level widget tutorial?

**To Reproduce**
1. in a jupyter notebook code cell:
2. import lux
3. import pandas as pd
4. df = pd.read_csv("https://people.sc.fsu.edu/~jburkardt/data/csv/addresses.csv")
5. df
6. Open the inspector
7. Click the toggle Pandas/lux button

**Important**: Make sure to provide a sample of (preferably synthetic) data 

**Expected behavior**
Click button to toggle, no error

**Screenshots**

**Debugging information**
Package Versions
----------------
               Version
        python 3.8.13 
           lux  0.5.1 
        pandas  1.4.2 
     luxwidget 0.1.11 
    matplotlib  3.5.2 
        altair  4.2.0 
       IPython 7.29.0 
     ipykernel  6.4.1 
    ipywidgets  7.6.5 
jupyter_client 6.1.12 
  jupyter_core  4.8.1 
jupyter_server  1.4.1 
    jupyterlab  3.2.1 
      nbclient  0.5.3 
     nbconvert  6.1.0 
      nbformat  5.1.3 
      notebook  6.4.5 
     qtconsole  5.1.1 
     traitlets  5.1.0 

Widget Setup
-------------
✅ Jupyter Notebook Running
✅ luxwidget is enabled

**Comment by dorisjlee** [comment]
Hi @aguamentiPatronum, Thank you for posting this issue! I took a look at this and tried to reproduce your issue. It seems like we are able to get the Toggle Button and widget to display.
![Screen Shot 2022-05-29 at 5 48 19 PM](https://user-images.githubusercontent.com/5554675/170898894-23e038e6-c669-48de-8674-5000be8a50ef.png)
The Chrome errors seems to be only happening on Jupyter Notebook (not Jupyter Lab) but the error messages are slightly different from what you're seeing. 
![Screen Shot 2022-05-29 at 5 55 37 PM](https://user-images.githubusercontent.com/5554675/170899327-6308df33-f3d9-4e7f-a926-5ba81d593666.png)
