### ISSUE TITLE
Supporting static graphics rendering 

### ISSUE THREAD

**Issue by dorisjlee** [lux-org/lux#62]
Scatterplots with large number of data points take a disproportionately long time to render on the frontend, due to the large number of points we have to draw. We should explore other rendering options that are faster, even if that means that the visualizations are non-interactive and static (e.g., just an image). For portability, we should try [other rendering options in Altair](https://altair-viz.github.io/user_guide/custom_renderers.html) first. Our current rendering mechanism is Canvas, and it's not entirely clear whether SVG would be faster or slower (see [[1]](https://www.educba.com/svg-vs-canvas/),[[2]](https://stackoverflow.com/questions/5882716/html5-canvas-vs-svg-vs-div)). If not, we could migrate to matplotlib as an alternative rendering backend and create static images that is then sent to the frontend.

**Comment by jrdzha** [comment]
@dorisjlee The upper limit of drawing is much higher now. This may not be necessary anymore. Moving away from live rendering would also disable hovering over points or bars (useful for outliers especially)...
